version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: nestmap-db
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: nestmap_test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d nestmap_test"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
