export enum AppErrorCode {
  UNKNOWN_ERROR = 'APP/UNKNOWN_ERROR',
  BAD_REQUEST = 'APP/BAD_REQUEST',
  UNAUTHORIZED = 'APP/UNAUTHORIZED',
  FORBIDDEN = 'APP/FORBIDDEN',
  NOT_FOUND = 'APP/NOT_FOUND',
  CONFLICT = 'APP/CONFLICT',
  VALIDATION_ERROR = 'APP/VALIDATION_ERROR',
  TOO_MANY_REQUESTS = 'APP/TOO_MANY_REQUESTS',
  INTERNAL_SERVER_ERROR = 'APP/INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE = 'APP/SERVICE_UNAVAILABLE',
}
